#!/bin/bash

cp /workspaces/.codespaces/.persistedshare/dotfiles/.bash_aliases ~/.bash_aliases
source ~/.bash_aliases

if [ -f /workspaces/github/script/setup-codespaces-orca ]; then
  echo "Adding Orca..."
  cd /workspaces/github
  script/setup-codespaces-orca
fi

# if [ -f /workspaces/github/bin/toggle-feature-flag ]; then
#  echo "Toggling feature flags..."
#  cd /workspaces/github
#  bin/toggle-feature-flag enable copilot-custom-models
#  bin/toggle-feature-flag enable copilot_custom_models_training_steps
# fi

# if [ -f /workspaces/github/script/setup-copilot ]; then
#  echo "Updating dotcom..."
#  cd /workspaces/github
#  git pull
#  echo "Setting up copilot..."
#  script/setup-copilot
# fi
